Add a command to redo GT vein cache
GTNewHorizons/VisualProspecting pull request #13
Opened 2022-05-16 15:19 UTC by MuXiu1997

ref: GTNewHorizons/GT-New-Horizons-Modpack#10273

Sometimes there are problems with the server cache, for example around the Spawn chunk
It wouldn't be a bad thing to have a command to redo the server cache

2022-06-05 14:03 UTC, MuXiu1997 commented
@Dream-Master 
If no one cares please close this pr

2022-06-05 16:15 UTC, glowredman commented on src/main/java/com/sinthoras/visualprospecting/database/RedoServerCacheCommand.java
> +import net.minecraft.client.resources.I18n;
This will crash on server-side

2022-06-05 16:19 UTC, glowredman requested changes

2022-06-05 16:19 UTC, glowredman commented on src/main/java/com/sinthoras/visualprospecting/database/RedoServerCacheCommand.java
> +        return I18n.format("visualprospecting.redoservercache.command");
Please use `net.minecraft.util.StatCollector#translateToLocal`, `I18n` is client-side only

2022-06-06 05:29 UTC, MuXiu1997 commented on src/main/java/com/sinthoras/visualprospecting/database/RedoServerCacheCommand.java
> +        return I18n.format("visualprospecting.redoservercache.command");
ty, done

2022-06-06 15:07 UTC, merged