Added hotkeys to toggle map overlays
GTNewHorizons/VisualProspecting pull request #33
Opened 2023-06-02 05:58 UTC by PolkageistHS

Mainly for the minimap but it affects both minimap and fullscreen map, toggling the ore/fluid overlays can help declutter the minimap when looking out for mobs or trying to navigate around without having to go into the fullmap screen every time.

2023-06-02 06:02 UTC, PolkageistHS commented
I know there's no true "right" way to add this but I haven't done much in java or mods in general so if there's a way better way to do it I'm all ears

2023-06-02 07:05 UTC, minecraft7771 requested changes

2023-06-02 07:05 UTC, minecraft7771 commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +    private void checkAndToggleOverlays() {
No need to cycle through the buttons. You can reference `ThaumcraftNodeButtonManager.instance` etc.

2023-06-02 07:05 UTC, minecraft7771 commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +    private void checkAndToggleOverlays() {
Nit: I'd like you rename `btn` to `button`, though I suppose you don't need the variable any longer, so just telling this for the future.

2023-06-02 11:53 UTC, miozune commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksClient.java
> +        MinecraftForge.EVENT_BUS.register(new HooksKey());
Since `KeyInputEvent` is posted to `FMLCommonHandler#eventBus`, no need to register to `MinecraftForge.EVENT_BUS`.
```suggestion
        FMLCommonHandler.instance().bus().register(new HooksKey());
```

2023-06-02 17:41 UTC, Dream-Master commented
@PolkageistHS

2023-06-02 20:02 UTC, PolkageistHS commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +    private void checkAndToggleOverlays() {
I should probably get to know the singleton pattern a bit more.

2023-06-02 20:12 UTC, minecraft7771 approved these changes

2023-06-02 20:14 UTC, merged

2023-06-03 04:01 UTC, miozune commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +        FMLCommonHandler.instance().bus().register(this);
Now this becomes duplicated registration

2023-06-03 04:05 UTC, PolkageistHS commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +        FMLCommonHandler.instance().bus().register(this);
Ahh, that's what you meant by the other review.  Any harm in keeping or should I clean one of them up?  And if so, which should be yeeted?

2023-06-03 04:15 UTC, miozune commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +        FMLCommonHandler.instance().bus().register(this);
I'm not sure about the effect, but cleaning it up would be nice. Either is fine, but removing the one in the constructor of `HooksKey` makes sense to me

2023-06-03 07:04 UTC, minecraft7771 commented on src/main/java/com/sinthoras/visualprospecting/hooks/HooksKey.java
> +        FMLCommonHandler.instance().bus().register(this);
True I didn't notice this.